/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'P2P',systemName:'企业采购管理平台',englishName:'PROCURE TO PAY',theme:{primary:'#176b5b',dark:'#173d38',accent:'#d18a2e'},workspace:'供应链中心 / 采购运营',fieldWorkspace:'华东采购组',period:'2026-08-01 · 周六',liveText:'ERP 与供应商门户连接正常',fieldContextLabel:'当前采购组织',fieldContext:'华东区 · 间接采购',fieldUser:'苏言',fieldRole:'采购专员',adminUser:'孟舟',adminRole:'采购运营经理',
 adminTitle:'采购运营控制塔',adminBreadcrumb:'采购管理 / 今日运营',adminSubtitle:'集中查看请购、寻源、订单、收货、发票和付款匹配状态。',exportAction:'导出采购日报',createAction:'创建寻源任务',chartTitle:'采购处理周期',chartSubtitle:'本月累计按时完成率 / 管控目标',chartLabels:['第1周','第2周','第3周','第4周','第5周','第6周','第7周','第8周','本周'],loadTitle:'品类采购负荷',loadSubtitle:'进行中任务占团队可处理能力',recordsTitle:'进行中采购事项',recordsSubtitle:'按交付风险、金额和承诺日期排序',issueTitle:'采购与付款风险',issueSubtitle:'需要采购运营协调处理的异常事项',
 recordName:'采购事项',itemName:'品类 / 物料',unitName:'供应商',batchName:'合同版本',planName:'申请金额',doneName:'已执行',exceptionName:'差异',unitLabel:'万元',listBreadcrumb:'采购执行 / 业务台账',listSubtitle:'统一管理请购审批、供应商寻源、采购订单、收货与三单匹配。',listSummary:[['今日新请购','28'],['执行中订单','31'],['待收货确认','9'],['交付风险','3',true]],tabs:['全部','待审批','寻源中','执行中','待匹配','已完成'],
 fieldBreadcrumb:'采购执行 / 我的工作台',fieldTitle:'采购专员工作台',fieldSubtitle:'当前 8 项执行中 · 3 个供应商报价待确认 · 采购专员苏言',fieldSecondary:'审批记录',reportAction:'更新进展',fieldNoticeTitle:'供应商与预算校验已通过',fieldNotice:'准入状态、预算余额、框架价格均已自动核验',steps:['请购审批','询比价','订单下达','收货验收','发票匹配'],documentAction:'查看采购策略',printAction:'下载询价单',resourceCardTitle:'框架协议状态',resourceValueLabel:'协议覆盖率',resourceHealthLabel:'价格有效率',quickSubtitle:'采购执行高频业务入口',quickActions:[['进展更新','/shopfloor/report','报价、订单与收货进度'],['供应商协同','/shopfloor/material','询价、澄清与交付承诺'],['品类目录','/shopfloor/resources','协议价格与可采购清单'],['风险上报','/shopfloor/andon','交期、质量与付款异常']],
 reportDefaults:[6,0],reportTitle:'采购进展更新',reportSubtitle:'记录执行数量、差异金额和采购过程说明。',reportSuccess:'采购进展已保存并进入业务复核',reportPlaceholder:'填写报价依据、交期承诺、收货差异或处理方案',reportFootnote:'提交后写入采购审计轨迹并通知相关责任人',ruleTitle:'采购控制规则',ruleSubtitle:'P2P-POLICY-2026 · V4.1',rules:[['三家询比价','金额 ≥ 5 万'],['订单容差','±2%'],['付款账期','45 天'],['供应商准入','有效',true]],fieldTotals:[['19','已完成事项'],['2','交付异常'],['7','待复核记录'],['97.1%','采购数据完整率']],
 adminMenus:[['/admin','home','采购控制塔'],['/admin/work-orders','order','采购事项'],['/admin/samples','box','供应商管理'],['/admin/schedule','calendar','采购日历'],['/admin/methods','process','策略与规则'],['/admin/reviews','quality','收货与匹配'],['/admin/resources','machine','品类目录'],['/admin/report','chart','采购分析']],fieldMenus:[['/shopfloor','home','我的工作台'],['/shopfloor/report','report','进展更新'],['/shopfloor/tasks','order','待办事项'],['/shopfloor/material','box','供应商协同'],['/shopfloor/resources','machine','品类目录'],['/shopfloor/andon','risk','风险上报',2]],
 moduleTitles:{tasks:['待办事项','查看审批、寻源、订单与匹配优先级'],material:['供应商协同','跟踪询价、澄清、交付和对账过程'],resources:['品类目录','管理协议商品、价格和有效期'],andon:['风险上报','登记交期、质量、收货与发票异常'],samples:['供应商管理','维护准入、绩效、资质和风险档案'],schedule:['采购日历','协调询价、交付、收货与付款节点'],methods:['策略与规则','维护采购策略、阈值和审批矩阵'],reviews:['收货与匹配','执行收货核验、三单匹配和差异确认'],report:['采购分析','分析节省、周期、合规率和供应风险']},tagline:'让每一笔采购从需求到付款都透明可控',storyTitle:'请购、寻源、订单与付款，<br/>在一条审计链上闭环。',storyText:'连接需求部门、采购团队、供应商与财务共享中心的采购数字底座。',pattern:[2,4,7,8,12,13,18,19,20,24,25,28,30],loginStats:[['97.1%','采购数据完整率'],['31','当前执行中订单'],['4.2 天','平均采购周期']],loginTitle:'企业采购运营中心',adminDemo:'采购 / 合规 / 分析',fieldDemo:'寻源 / 订单 / 协同'
}
export const records=[{no:'PR-260801-018',name:'研发测试设备采购',code:'LAB-EQP',unit:'澄岳仪器',group:'华东采购组',plan:86,done:62,exception:3,due:'08-04',batch:'FA-2026-V2',status:'执行中',progress:72,priority:'加急'},{no:'PO-260801-021',name:'云资源年度框架续签',code:'CLOUD-SVC',unit:'云端科技',group:'间接采购组',plan:128,done:96,exception:0,due:'08-05',batch:'IT-2026-V4',status:'待匹配',progress:75,priority:'正常'},{no:'RFQ-260802-006',name:'工厂劳保用品集采',code:'PPE-2026',unit:'三家比价',group:'生产采购组',plan:42,done:0,exception:0,due:'08-06',batch:'RFQ-D1',status:'寻源中',progress:28,priority:'正常'},{no:'PO-260728-015',name:'包装材料季度订单',code:'PACK-Q3',unit:'华峰包装',group:'生产采购组',plan:65,done:65,exception:1,due:'08-01',batch:'PACK-V3',status:'已完成',progress:100,priority:'正常'},{no:'PR-260801-024',name:'华南仓储服务采购',code:'WH-SVC',unit:'待定标',group:'物流采购组',plan:180,done:92,exception:8,due:'08-03',batch:'LOGI-V1',status:'业务确认中',progress:51,priority:'关注'}]
export const resources=[{code:'FA-IT-03',name:'IT 设备框架协议',unit:'云端科技',status:'运行',health:93,value:'87',valueUnit:'%',note:'协议目录 124 项可用'},{code:'FA-PPE-05',name:'劳保用品框架协议',unit:'安健实业',status:'运行',health:89,value:'45',valueUnit:'天',note:'价格有效至 2026-09-15'},{code:'FA-LOGI-08',name:'物流服务协议',unit:'华运物流',status:'报警',health:63,value:'2',valueUnit:'项',note:'两条线路价格即将到期'}]
export const reviews=[{no:'MATCH-260801-032',title:'研发设备三单匹配',type:'发票匹配',detail:'86 万元 · 孟舟',result:'待确认'},{no:'GR-260801-011',title:'云资源服务验收',type:'收货复核',detail:'12 个服务项 · 苏言',result:'通过'},{no:'RISK-260728-018',title:'仓储服务报价偏差调查',type:'合规评审',detail:'RISK-2607-02',result:'异常'}]
export const adminMetrics=[['本月采购额','2,846 万','较计划节省 4.6%','blue'],['采购合规率','97.8%','目标值 ≥ 96%','green'],['待匹配发票','9','其中 2 项加急','orange'],['供应风险','3','1 项影响交付','red']]
export const fieldMetrics=[['今日待办','8','21 个采购节点','blue'],['已完成','19','本周完成率 73%','green'],['待业务复核','7','材料已完整提交','orange'],['协议状态','可用','IT 设备框架','slate']]
export const chartActual=[9,19,31,43,55,64,74,86,94],chartTarget=[10,22,34,46,58,69,80,90,98]
export const loads=[['生产物料',92,'13 项执行中'],['IT 与服务',81,'9 项执行中'],['物流仓储',73,'6 项执行中'],['行政采购',55,'4 项执行中']]
export const issues=[{type:'交付',title:'研发设备交期可能延迟',detail:'供应商承诺晚于需求 3 天',status:'协调中'},{type:'匹配',title:'云资源发票金额与订单不符',detail:'差异 1.8 万元 · 等待供应商红冲',status:'处理中'},{type:'合规',title:'华南仓储报价缺少成本拆分',detail:'定标材料不完整',status:'待补充'}]
